In [1]:
import numpy as np

# Перемножение матриц

Напишите две функции, каждая из которых перемножает две квадратные матрицы: одна без использования встроенных функций numpy, а другая --- с помощью numpy. На вход первой задаче подаются списки размера size по size элементов в каждом. На вход второй задаче подаются объекты типа np.ndarray --- квадратные матрицы одинакового размера. 

Первая функция должна возвращать список списков, а вторая -- np.array.

In [17]:
# Перемножаем без numpy
first = [[1, 2],
         [3, 4]]
second = [[5, 6],
          [7, 8]]
def no_numpy_mult(first, second):
    result = [[0 for j in range(len(second))] for i in range(len(second[0]))]
    
    for i in range(len(first)):
        for j in range(len(first)):
            for k in range(len(first)):
                result[i][j] += first[i][k] * second[k][j]
    
    return result
no_numpy_mult(first, second)

[[19, 22], [43, 50]]

In [21]:
# Перемножение с numpy
A = [[1, 2],
    [3, 4]]
B = [[5, 6],
    [7, 8]]
first = np.array(A)
second = np.array(B)
def numpy_mult(first, second):

    return np.matmul(first, second)
numpy_mult(first, second)

array([[19, 22],
       [43, 50]])

# Скалярное произведение векторов

Вам подаются на вход два вектора a и b в трехмерном пространстве. Реализуйте их скалярное произведение с помощью numpy и без. 

In [24]:
# Скалярное произведение без numpy
v1 = [1, 3, 4]
v2 = [5, 9, 14]
def no_numpy_scalar(v1, v2):
    result = 0
    for x, y in zip(v1, v2):
        result += x * y
    return result
no_numpy_scalar(v1, v2)

88

In [25]:
# Скалярное произведение с numpy
v1 = [1, 3, 4]
v2 = [5, 9, 14]
def numpy_scalar (v1, v2):
    return np.dot(v1, v2)
numpy_scalar(v1, v2)

88

# Сумму четных элементов на диагонали матрицы

Напишите функцию, которая находит сумму четных элементов на главной диагонали квадратной матрицы (именно чётных элементов, а не элементов на чётных позициях!). Если чётных элементов нет, то вывести 0. Используйте библиотеку numpy.

In [33]:
A = [[12, 3, 4, 8],
    [10, 5, 32, 90],
    [65, 94, 54, 14]]
a = np.array(A)
def diag_2k(a):
    even_elem = [elem for elem in np.diagonal(a) if elem % 2 == 0]
    
    return sum(even_elem)
    
diag_2k(a)

66

# Задание с двумерным массивом и непонятным условием

На вход дан двумерный массив XX. Напишите функцию, которая для каждой строчки x = (x_1, x_2, \ldots, x_n)x=(x 
1
​
 ,x 
2
​
 ,…,x 
n
​
 ) массива XX строит строчку s = (s_1, s_2, \ldots, s_n)s=(s 
1
​
 ,s 
2
​
 ,…,s 
n
​
 ), где s_k=x_1+...+x_ks 
k
​
 =x 
1
​
 +...+x 
k
​
 , а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и XX.

In [36]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
def cumsum(A):

    return np.cumsum(A, axis=-1)
cumsum(A)

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]])

# Склеивание

Задан двумерный массив XX. Для каждой строчки массива XX необходимо сделать следующее преобразование.

Пусть дана строчка xx. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число aa (значение по умолчанию a = 1a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив xx с преобразованным xx и вернуть на выход функции (естественно, выход должен быть numpy-массивом).

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива XX. Массив XX при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
x = [[100, 200, 300, 400, 500100,200,300,400,500]] -> [[100, a, 300, a, 500100,a,300,a,500]] -> [[500^3, a, 300^3, a, 100^3500 
3
 ,a,300 
3
 ,a,100 
3
 ]] -> склеиваем -> [[100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3100,200,300,400,500,500 
3
 ,a,300 
3
 ,a,100 
3
 ]]

In [66]:
# X = np.array([[100, 200, 300, 400, 500100,200,300,400,500]])
X = np.array([[2, 3, 4, 5, 6]])
def transform(X, a=1):
    B = []
    D = X.copy()
    for i in range(X.shape[0]):
        for j in range(len(X[i])):
            if (j % 2 == 1):
                D[i][j] = a
            elif (j % 2 == 0):
                D[i][j] = np.power(D[i][j], 3)
        reversed = np.flip(D[i], axis=0)
        B.append(reversed)
    B = np.asarray(B)
    result = np.hstack((X, B))
    return result
    
    

transform(X)

array([[  2,   3,   4,   5,   6, 216,   1,  64,   1,   8]])

# Последнее задание

С помощью numpy написать функцию для кодирования массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух numpy-векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array([1, 2, 3, 1, 5, 2, 3]), np.array([1, 2, 2, 2, 2, 1, 2]))

In [67]:
def encode(x):
    x = np.asanyarray(x)
    n = x.shape[0]
    if n == 0:
        return np.array([]), np.array([]), np.array([])
    else:
        loc_run_start = np.empty(n, dtype=bool)
        loc_run_start[0] = True
        np.not_equal(x[:-1], x[1:], out=loc_run_start[1:])
        run_starts = np.nonzero(loc_run_start)[0]
        run_values = x[loc_run_start]
        run_lengths = np.diff(np.append(run_starts, n))

        return run_values, run_lengths